### ISSUE TITLE
Termux app

### ISSUE THREAD

**Issue by jjoeshua** [Cyber-Dioxide/Wifi-Brute#4]
I follow the install instructions on termux on phone, I give permission storage,phone is rooted install everything right and when I start app with python3 wifi-brute force ,got this error:
$ python3 wifi-brute.py
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/
Could not fetch URL https://pypi.org/simple/pywifi/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pywifi/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pywifi (from versions: none)
ERROR: No matching distribution found for pywifi
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Wifi-Brute/wifi-brute.py", line 8, in <module>
    from pywifi import const
ModuleNotFoundError: No module named 'pywifi'
$

**Comment by MrNkolima** [comment]
> I follow the install instructions on termux on phone, I give permission storage,phone is rooted install everything right and when I start app with python3 wifi-brute force ,got this error: $ python3 wifi-brute.py WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/ WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/ WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/ WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pywifi/ Could not fetch URL https://pypi.org/simple/pywifi/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pywifi/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping ERROR: Could not find a version that satisfies the requirement pywifi (from versions: none) ERROR: No matching distribution found for pywifi WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available. Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping WARNING: There was an error checking the latest version of pip. Traceback (most recent call last): File "/data/data/com.termux/files/home/Wifi-Brute/wifi-brute.py", line 8, in from pywifi import const ModuleNotFoundError: No module named 'pywifi' $

Yap and I think it's a bug

**Comment by Cyber-Dioxide** [comment]
> 

Try these commands:

apt install openssl
pip install pywifi

**Comment by Roinspire** [comment]
Try:
apt upgrade

**Comment by Mysterious-lover** [comment]
first you update and upgrade the termux  terminals using pkg update and pkg update. the apply the code with using pkg and apt command

**Comment by Jhankritlakhmara** [comment]
Still not working
pip install pywifi
